### ISSUE TITLE
Unable to Mock S3Client

### ISSUE THREAD

**Issue by kheriox-technologies** [m-radzikowski/aws-sdk-client-mock#127]
Trying to Mock S3Client. Receiving below error when I try to mock it as per the docs. 
```
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';
const s3ClientMock = mockClient(S3Client);
```
```
Argument of type 'typeof S3Client' is not assignable to parameter of type 'InstanceOrClassType<Client<ServiceInputTypes, MetadataBearer, any>>'.
  Type 'typeof S3Client' is not assignable to type 'ClassType<Client<ServiceInputTypes, MetadataBearer, any>>'.
    The types of 'prototype.middlewareStack.add' are incompatible between these types.
      Type '{ (middleware: InitializeMiddleware<ServiceInputTypes, ServiceOutputTypes>, options?: (InitializeHandlerOptions & AbsoluteLocation) | undefined): void; (middleware: SerializeMiddleware<...>, options: SerializeHandlerOptions & AbsoluteLocation): void; (middleware: BuildMiddleware<...>, options: BuildHandlerOptions & ...' is not assignable to type '{ (middleware: InitializeMiddleware<ServiceInputTypes, MetadataBearer>, options?: (InitializeHandlerOptions & AbsoluteLocation) | undefined): void; (middleware: SerializeMiddleware<...>, options: SerializeHandlerOptions & AbsoluteLocation): void; (middleware: BuildMiddleware<...>, options: BuildHandlerOptions & Abso...'.
```

```
"@aws-sdk/client-s3": "^3.200.0"
 "aws-sdk-client-mock": "^2.0.0",
```

**Comment by m-radzikowski** [comment]
Please read the [Mixed @aws-sdk/types versions
](https://github.com/m-radzikowski/aws-sdk-client-mock#mixed-aws-sdktypes-versions) section of README.

**Comment by sebsonjura** [comment]
I would love to resolve my s3client problems here as well. But since I am installing ONLY the s3 client, I have no way seeing the sdk version installed in my package.json. 

My errors are just whn I try to pass something to resolve. Basically ALL examples for this lib i and S3 and stack overflow dow't work for me. 

this
```
      s3ClientMock.on(GetObjectCommand).resolves({
        Body: fs.createReadStream('path/to/some/file.csv'),
      });
 ```
 
 gives me this error:
 
 Argument of type '{ Body: any; }' is not assignable to parameter of type 'CommandResponse<MetadataBearer>'.
  Object literal may only specify known properties, and 'Body' does not exist in type 'CommandResponse<MetadataBearer>'.

**Comment by dreed-trek10** [comment]
I had to run `npm i @aws-sdk/types` to get it to work.  Hope that helps.
