### ISSUE TITLE
Using S3 PutObjectCommand with a readable stream breaks

### ISSUE THREAD

**Issue by ypicard** [m-radzikowski/aws-sdk-client-mock#134]
**Checklist**

**Bug description**

I have the following piece of code I am trying to test:
```javascript
const command = new PutObjectCommand({ Bucket: bucket, Key: key, Body: fs.createReadStream(path) });
await s3Client.send(command);
fs.rmSync(path);
```

My test:
```javascript

const s3Mock = mockClient(S3Client);
s3Mock.on(PutObjectCommand).resolves({});
...
expect(s3Mock).toHaveReceivedCommandWith(PutObjectCommand, {
            Bucket: bucket,
            Key: key,
            Body: expect.anything(),
        });
```

The test itself passes but returns the following error:
```bash
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '<filepath>'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '<filepath>'
}
```

I think this may be due to some internals of this library:

1. I create a ReadStream
2. I pass it to the `PutObjectCommand` and upload it to S3. Normal code execution would close the stream once this is one, but I suspect this library to keep it open for some reason when using a mocked client?
3. The file is deleted.
4. This library tries to do assertions on the mocked command and its content and refers to the still referenced stream object, which points to a non-existing file.
5. It breaks.

**Environment**

- Node version: v16.15.0
- Testing lib and version: Jest v29.3.1
- Typescript version: v4.9.3
- AWS SDK v3 Client mock version: v2.0.0
- AWS JS SDK libs and versions:
  - @aws-sdk/client-s3: v3.212.0
  - @aws-sdk/client-sns: v3.212.0
  - @aws-sdk/client-sqs: v3.212.0

**Comment by m-radzikowski** [comment]
Interesting problem.

I think your explanation of what happens is almost correct:

1. I create a ReadStream
1. I pass it to the PutObjectCommand and upload it to S3. Normal code execution would close the stream once this is one, but **the mocking library does nothing with it**.
1. The file is deleted.
1. **Node tries to close the open stream and the end of the process, but the file the handler references does not exist anymore.**
1. It breaks.

I don't intend to add any special behavior to particular Commands, like here, to close the stream passed in `PutObjectCommand`. It would be going down a rabbit hole full of edge cases.

So you need to handle closing the stream in your test.

There are two problems here:

1. You can't close the stream after calling the tested method, because the file is removed in this method. You must close it in the scope of `s3Client.send()` execution. Thankfully, you can use `callsFake()` function to implement your custom behavior for processing sent Command, like closing the passed stream.
1. The `stream.close()` or `stream.destroy()` calls are asynchronous, and you need to wait for the stream to be actually closed until proceeding to removing the file. But you can pass a callback to `stream.close()`.

In the end, the solution I come up with is:

```ts
import {PutObjectCommand, PutObjectCommandInput, S3Client} from '@aws-sdk/client-s3';
import {mockClient} from 'aws-sdk-client-mock';
import * as fs from 'fs';
import {ReadStream} from 'fs';
import 'aws-sdk-client-mock-jest';

const upload = async (path: string) => {
    const s3Client = new S3Client({});
    const command = new PutObjectCommand({Bucket: 'qq', Key: 'ww', Body: fs.createReadStream(path)});
    await s3Client.send(command);
    fs.rmSync(path);
};

it('uploads and removes the file', async () => {
    fs.writeFileSync('test.txt', 'Hello');

    const s3Mock = mockClient(S3Client);
    // custom handling of PutObjectCommand
    s3Mock.on(PutObjectCommand).callsFake(async (input: PutObjectCommandInput) => {
        const stream = input.Body as ReadStream;
        // close the passed-in stream
        await new Promise<void>((resolve) => stream.close(() => resolve()));
    });

    await upload('test.txt');

    expect(s3Mock).toHaveReceivedCommandWith(PutObjectCommand, {
        Bucket: 'qq',
        Key: 'ww',
        Body: expect.anything(),
    });
});
```

Please let me know if that works for you!
