### ISSUE TITLE
Mock does not reset for other tests

### ISSUE THREAD

**Issue by jatinmehrotra** [m-radzikowski/aws-sdk-client-mock#153]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

I am trying to unit test lambda function.

I am trying to test 5xx status code in my lambda. In order to test it I want to remove mock so that credential error (CredentialsProviderError: Could not load credentials from any providers)occurs (which is obvious). But since the mock of the first describe is still active I am not able to test it. How do I reset the mock for different describe test cases

The only way I intend to work if I comment on the first describe block i.e don't use the mock at all.

Tried to follow this too but didnt worked https://github.com/m-radzikowski/aws-sdk-client-mock/issues/83

I have posted this on stackoverflow too for [reference.](https://stackoverflow.com/q/75945593/13126651)

### Reproduction

```
import { APIGatewayProxyResult } from 'aws-lambda';
import { main } from "../../lib/src/lambda/approval-handler";
import { mockClient } from "aws-sdk-client-mock";
import {
    CodePipelineClient
} from "@aws-sdk/client-codepipeline";
import { event, queryStringParameters } from "../utils/lambda-event"


describe("Successful Approve or Deny", () => {. //this works

    const pipelineClientMock = mockClient(CodePipelineClient);

    beforeEach(() => {
        pipelineClientMock.reset();
    });

    it("returns a 301 response with a redirect location if all required query parameters are provided", async () => {

        pipelineClientMock.resolves({})

        const result: APIGatewayProxyResult = await main(event);
        expect(result.statusCode).toEqual(301);
    });

})


describe("When Approval or Deny is not sent successfully", () => { //this fails because mock is still active

    it("returns a 502 error response if any of the required query parameters are missing", async () => {

        const result: APIGatewayProxyResult = await main(event);
        expect(result.statusCode).toEqual(502);
    });
});
```

### Environment

- Node version: LTS
- Testing lib and version:  Jest : "^27.5.1",
- Typescript version: "~3.9.7"
- AWS SDK v3 Client mock version: "^2.1.1"
- AWS JS SDK libs and versions:   "@aws-sdk/client-codepipeline": "^3.231.0",

**Comment by jatinmehrotra** [comment]
@m-radzikowski 

I solved it by moving a particular instance of mock client inside describe block and using `.restore `. May be updating a readme would help a lot to others users who will face a similar problem, because there is a mention to `.reset` but not to `.restore`


I would be happy to update the project readme under the Lambda section by adding this as a use case. Let me know if you would like me to do this

```
 describe("When Approval or Deny is not sent successfully", () => {
    const pipelineClientMock = mockClient(CodePipelineClient);
    beforeEach(() => {
        pipelineClientMock.restore();
    });

    it("returns a 502 error response if any of the required query parameters are missing", async () => {

        const result: APIGatewayProxyResult = await main(event);
        expect(result.statusCode).toEqual(502);
    });
});
```

**Comment by m-radzikowski** [comment]
Hey, sorry again for not responding earlier.

Mocks use Sinon.js Stubs (https://sinonjs.org/releases/latest/stubs/). The mocked client exposes the `send()` method stub itself as well as some Sinon methods, like `reset()` and `restore()` (see https://m-radzikowski.github.io/aws-sdk-client-mock/classes/AwsStub.html).

As you discovered, after calling `mockClient()` on a class, all further instances of this client will be mocked. There is nothing that would reset this between tests.

In the example in the README, in the `beforeEach` we call `mock.reset()`. This does not remove the mock, only cleans it from any configuration and history, so tests are independent. So that's a best practice.

In most cases, we won't call `mock.restore()` at all, simply because we want to have our client mocked for every test, and only change how that mock behaves.

But if we have such need, the best solution would be to call `restore()` in the `afterEach()` / `afterAll()`. For example:

```ts
describe("block with mocked client", () => {
    let pipelineClientMock: AwsClientMock<CodePipelineClient>;

    beforeAll(() => {
        pipelineClientMock = mockClient(CodePipelineClient);
    });

    beforeEach(() => {
        pipelineClientMock.reset();
    });

    afterAll(() => {
        pipelineClientMock.restore();
    });

    it("...", async () => {
        // client is mocked here
    });
});

describe("block without mocked client", () => {
    it("...", async () => {
        // client is NOT mocked here
    });
});
```

For the README - let me update it with an explanation on both the `reset()` and `restore()` methods, as you are correct that it's missing.

**Comment by jatinmehrotra** [comment]
@m-radzikowski Can i do it as a PR?
