### ISSUE TITLE
Argument of type 'typeof S3Client' is not assignable to parameter of type 'InstanceOrClassType<Client<ServiceInputTypes, MetadataBearer, SmithyResolvedConfiguration<HttpHandlerOptions>>>'.

### ISSUE THREAD

**Issue by moltar** [m-radzikowski/aws-sdk-client-mock#168]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Upgrading from `3.362.0` breaks types `3.363.0`.

### Reproduction

Repro: [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZQMwGEA2wCmA7eAXzgDMoIQ4ByAAQEMB3AZwFomATAawHoBjbfDDaoqAKFCRYiOCAi9OWXATjEyFao1YdOLfkqGz5Y0bwh4m8JqjgBeGXIUCCACjSLBASlGigA)

### Environment

- Node version: 16
- Testing lib and version: Jest
- Typescript version: 5
- AWS SDK v3 Client mock version: 2.2.0
- AWS JS SDK libs and versions: 3.363.0

**Comment by air2** [comment]
It looks like it has to do with the different between __Metabearer and Metabearer

**Comment by rbargholz** [comment]
A fix for us was to pin all `@aws-sdk/*` packages to `3.362.0` in the meantime.

**Comment by m-radzikowski** [comment]
Such errors were usually a result of having different versions of `aws-sdk/types` installed (see https://github.com/m-radzikowski/aws-sdk-client-mock#mixed-aws-sdktypes-versions). But it's not the case here.

v3.363.0 of AWS SDK migrated many dependencies from `@aws-sdk/*` to `@smithy/*`:

- https://github.com/aws/aws-sdk-js-v3/pull/4873
- https://github.com/awslabs/smithy-typescript

Which is probably the cause here. I will investigate the possibility of moving from using `@aws-sdk/types` to `@smithy/types`, which may be the solution. But until then, yes, you have to stay on the v3.362.0.

**Comment by aka-somix** [comment]
I am having the same issue and cannot rollback to 3.362.0 because of vulnerability issue with that version.
Do we have any idea on how much time it will need to fix this?

I am kind of in a hurry, I have a deploy on monday and I need my test suite to be all green 😭

**Comment by moltar** [comment]
@aka-somix What vulnerability issues are there with 3.362.0?

> I am kind of in a hurry, I have a deploy on monday

Maybe propose a PR then? 😛

**Comment by m-radzikowski** [comment]
> I am having the same issue and cannot rollback to 3.362.0 because of vulnerability issues with that version. Do we have any idea on how much time it will need to fix this?
> 
> I am kind of in a hurry, I have a deploy on monday and I need my test suite to be all green 😭

Best case scenario is I fix this during the weekend, assuming everything goes smoothly (which I kind of doubt). This is an open-source library, feel free to submit a PR.

**Comment by aka-somix** [comment]
@moltar I was just trying to get insights on this bug rather than make pressure on the resolution.
Honestly, it is way easier for me to move away from this library since I am only mocking a DDB table, given how little time I have 😄.

Anyway, I am deleting the vulnerability part on my previous comment as it is in fact **incorrect** and I do not want to create confusion (I was just reported incorrectly, we were upgrading from a way lower.

Thank you @m-radzikowski for the update 🙂

**Comment by m-radzikowski** [comment]
It seems like changing `@aws-sdk/types` to `@smithy/types` was enough (0865065290b77fcfbfc6cf4a7db7c43448d1fcc1).

I've released v3.0.0 compatible with AWS SDK v3.363.0 (and hopefully above).

**Comment by moltar** [comment]
Thank you Maciej!!
