### ISSUE TITLE
Upload throws error when using mocked S3 client

### ISSUE THREAD

**Issue by jesterhazy** [m-radzikowski/aws-sdk-client-mock#206]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

The Upload class (from `@aws-sdk/lib-storage`) throws a TypeError when used with a mocked S3 client.

Trace:

```
TypeError: Cannot read properties of undefined (reading 'requestHandler')
    at _Upload.__uploadUsingPut (~/mock-s3-upload-issue/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:201:41)
    at _Upload.__doConcurrentUpload (~/mock-s3-upload-issue/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:280:29)
    at async Promise.all (index 0)
    at async _Upload.__doMultipartUpload (~/mock-s3-upload-issue/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:366:5)
    at async _Upload.done (~/mock-s3-upload-issue/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:190:12)
```

### Reproduction

```
const {mockClient} = require('aws-sdk-client-mock');
const {S3Client, PutObjectCommand} = require('@aws-sdk/client-s3');
const {Upload} = require('@aws-sdk/lib-storage');

class S3ClientWrapper {        
    constructor(client) {
        this.client = client;
    }

    async doUpload(bucket, key, data) {
        const upload = new Upload({
            client: this.client,
            params: {
                Bucket: bucket,
                Key: key,
                Body: data
            }
        });

        const response = await upload.done();
        console.log(response);        
    }
}


async function main() {
    const s3Mock = mockClient(S3Client);
    s3Mock.on(PutObjectCommand).resolves({});

    const wrapper = new S3ClientWrapper(s3Mock);

    await wrapper.doUpload('bucket', 'key', 'some data');
}

main();
```

### Environment

- Node version: v16.15.1 (or any)
- Testing lib and version: any
- Typescript version: any
- AWS SDK v3 Client mock version: 2.2.0 or 3.0.1
- AWS JS SDK libs and versions:
    - "@aws-sdk/client-s3": "^3.495.0", // or 3.321.0
    - "@aws-sdk/lib-storage": "^3.495.0" // or 3.321.0

**Comment by paul-uz** [comment]
Seems to have broken with the latest SDK v3 versions

**Comment by jesterhazy** [comment]
Can you identify a version this works on? The lines that the SDK throws on
haven’t been modified recently (7-8 months or more).

**Comment by m-radzikowski** [comment]
@jesterhazy the problem is you are providing the `mockClient(S3Client)` output as an SDK Client to the `Upload`. The `mockClient()` returns `AwsClientStub`, an object with methods to set up mock behavior. It's not the Client that you create with `new S3Client()`.

In line 30 of your snippet you should create and pass a new S3 Client with `new S3Client()` to the `S3ClientWrapper`.

Also, please see [the example in the README](https://github.com/m-radzikowski/aws-sdk-client-mock?tab=readme-ov-file#lib-storage-upload) on mocking `lib-storage` - you will need to mock `CreateMultipartUploadCommand` and `UploadPartCommand`.
