### ISSUE TITLE
3.1.0 / 4.0.0 breaks existing test-suite/build with Invalid Chai property: toHaveReceivedCommandWith on vitest

### ISSUE THREAD

**Issue by WtfJoke** [m-radzikowski/aws-sdk-client-mock#216]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

When we upgrade from version 3.0.1 to 3.1.0 our build/tests break.

Maybe related to https://github.com/m-radzikowski/aws-sdk-client-mock/pull/198

### Reproduction

1. Clone https://github.com/WtfJoke/aws-sdk-client-mock-reproducer-3.1.0
2. `npm install`
3. `npm run build` or `npm run test` fails

[Commit](https://github.com/WtfJoke/aws-sdk-client-mock-reproducer-3.1.0/commit/0f0edcd418f2dd81ff7e3bf7c15b4bf1f318d7c5) is broken (updates the dependency to 3.1.0), where as the [initial commit](https://github.com/WtfJoke/aws-sdk-client-mock-reproducer-3.1.0/commit/b51de61f82161ab083362c2f0ddd75abfeb9d532) works

### Environment

- Node version: v20.11.0
- Testing lib and version: vitest 1.4.0
- Typescript version: 5.4.3
- AWS SDK v3 Client mock version: 3.1.0
- AWS JS SDK libs and versions: @aws-sdk/client-secrets-manager v3.535.0
    -

**Comment by jurijzahn8019** [comment]
Hi, 

the `expect` is supposed to be a global which works with both jest and vitest (if globals: true).

importing it from the transitive dependency breaks functionality with vitest. 

https://github.com/m-radzikowski/aws-sdk-client-mock/blob/178e72c9e87a384fc032b14aa8831a30b29d6e6b/packages/aws-sdk-client-mock-jest/src/jestMatchers.ts#L7

**Comment by m-radzikowski** [comment]
I'm sorry for the problem and unexpected breaking change. However, the `aws-sdk-client-mock-jest` package was created with Jest in mind, and the ability to use it with Vitest as-is was not a nice addition (see #139).

You are right that the breaking change is #198, which adds an explicit dependency on the `expect`. This was done to accommodate Jest with and without using globals (#180).

That being said, I would love to support Vitest properly, including unit tests not to break anything in the future. I found a similar case in https://github.com/testing-library/jest-dom/pull/511. Their solution provides three different imports for Jest and Vitest:

```ts
import '@testing-library/jest-dom'; // default for Jest
import '@testing-library/jest-dom/jest-globals'; // for Jest using @jest/globals
import '@testing-library/jest-dom/vitest'; // for Vitest
```

and I think something similar could be done here. We have the current import for Jest:

```ts
import 'aws-sdk-client-mock-jest';
```

and a separate one could be created for Vitest:

```
import 'aws-sdk-client-mock-jest/vitest';
```

If someone is willing to give it a try and make a PR - I would be glad to review it. Otherwise, I can't commit to any specific timeline from myself.

**Comment by rehos** [comment]
While migrating from jest to vitest also stumbled upon this issue. I was able to resolve this by replacing aws-sdk-client-mock-jest with [aws-sdk-client-mock-vitest](https://github.com/stschulte/aws-sdk-client-mock-vitest)

**Comment by m-radzikowski** [comment]
The latest v4.1.0-beta.0 adds proper support for vitest thanks to @YiCChi

You can test it, I'll release it as a regular version if no one reports any problems.

See https://github.com/m-radzikowski/aws-sdk-client-mock?tab=readme-ov-file#vitest for instructions.
